version: "3.8"




services:
  auth-server:
    build: ./auth-server
    container_name: auth-server
    # Auto restart
    restart: unless-stopped
    # Expose port 443 (matches nftables)
    ports:
      - "443:443"
    environment:
    # JWT secret configured as an environment variable
      - JWT_SECRET=super_secret_key_for_smarttraffic
      - TOKEN_EXPIRES_IN=3600
