version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"   # Puerto externo para los microservicios
    environment:
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      # --- KRaft (sin ZooKeeper) ---
      CLUSTER_ID: "Jc83HgZES8Opf-6cxduOJg"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # --- Listeners ---
      # INTERNAL: para comunicación interna entre contenedores Docker
      # EXTERNAL: para que otras VMs accedan al broker
      # CONTROLLER: para el rol de controller en KRaft
      KAFKA_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://10.0.1.139:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      # --- Configuración de un solo nodo ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    volumes:
      - ./kafka-data:/var/lib/kafka/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP, para microservicios
      - "15672:15672"  # Panel web (podemos verlo por túnel SSH)
    environment:
      - RABBITMQ_DEFAULT_USER=smart
      - RABBITMQ_DEFAULT_PASS=smartpassword
    networks:
      - backend

networks:
  backend:
    driver: bridge
