version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"   # Puerto externo para los microservicios
    environment:
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      # --- KRaft (sin ZooKeeper) ---
      CLUSTER_ID: "Jc83HgZES8Opf-6cxduOJg"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Configura los listeners de Kafka:
      # - INTERNAL: para comunicación interna entre contenedores Docker
      # - EXTERNAL: para permitir el acceso de otras VMs al broker (por ejemplo, desde vm-core)
      # - CONTROLLER: necesario para el rol de controller en KRaft (sin ZooKeeper)
      KAFKA_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka:9093"
      # Anuncia las direcciones donde el broker Kafka puede ser contactado por los clientes:
      # INTERNAL (acceso interno Docker), EXTERNAL (acceso desde la red, aquí la IP privada de la VM)
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://10.0.1.139:9092"
      # Mapea cada listener al protocolo PLAINTEXT (sin autenticación/SSL)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      # Especifica que los brokers se comunicarán entre sí usando el listener INTERNAL
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      # --- Configuración de un solo nodo ---
      # Factor de replicación para los offsets
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Factor de replicación para los transacciones
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Factor de replicación para los logs de transacciones
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    volumes:
      - ./kafka-data:/var/lib/kafka/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP, para microservicios
      - "15672:15672"  # Panel web (podemos verlo por túnel SSH)
    environment:
      # RabbitMQ default user
      - RABBITMQ_DEFAULT_USER=smart
      # RabbitMQ default password
      - RABBITMQ_DEFAULT_PASS=smartpassword
    networks:
      - backend

networks:
  backend:
    driver: bridge
