services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"   # broker para los microservicios
    environment:
      # --- KRaft (sin Zookeeper) ---
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # --- Listeners ---
      # 9092 = broker para clientes
      # 9093 = listener interno de controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # IMPORTANTE: IP de la VM data (10.0.1.139)
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.0.1.139:9092

      # Para desarrollo, que cree topics si hace falta
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    volumes:
      - ./kafka-data:/bitnami/kafka
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP (para tus microservicios)
      - "15672:15672"  # Panel web (solo para pruebas desde tu PC v√≠a SSH tunnel si quieres)
    environment:
      - RABBITMQ_DEFAULT_USER=smart
      - RABBITMQ_DEFAULT_PASS=smartpassword
    networks:
      - backend

networks:
  backend:
    driver: bridge
